// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDU53L7SAH79JoQI5JylExg3vBm6EgO8J4',
    appId: '1:505794512227:web:511ac845f9c3db8c70bf56',
    messagingSenderId: '505794512227',
    projectId: 'apolli-db',
    authDomain: 'apolli-db.firebaseapp.com',
    storageBucket: 'apolli-db.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOAm4VM1OXAyyruCowT-UGd1ImPt7xTlI',
    appId: '1:505794512227:android:9a00eb100c738a5170bf56',
    messagingSenderId: '505794512227',
    projectId: 'apolli-db',
    storageBucket: 'apolli-db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEYqOE8ulCWgoF9-q6kh1oFL4GOwxxTEo',
    appId: '1:505794512227:ios:eee338e91b459c2370bf56',
    messagingSenderId: '505794512227',
    projectId: 'apolli-db',
    storageBucket: 'apolli-db.appspot.com',
    iosBundleId: 'com.example.apolli',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEYqOE8ulCWgoF9-q6kh1oFL4GOwxxTEo',
    appId: '1:505794512227:ios:9831a638d1e677c270bf56',
    messagingSenderId: '505794512227',
    projectId: 'apolli-db',
    storageBucket: 'apolli-db.appspot.com',
    iosBundleId: 'com.example.apolli.RunnerTests',
  );
}
